services:
  cyberclock-userbot:
    build:
      context: .
    container_name: cyberclock-userbot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TZ=${TZ}
    volumes:
      - ./assets:/app/assets
      - ./session:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
